const TOKEN_KINDS = ['SupportingTokens'],
  TOKEN_TYPES = ['UsernameToken'],
  ATRIBUTE_INCLUDE_TOKEN = 'IncludeToken',
  POLICY_TAG = 'Policy',
  NO_PASSWORD_TAG = 'NoPassword',
  HASH_PASSWORD_TAG = 'HashPassword',
  NORMAL_PASSWORD_TAG = 'Normal',
  USERNAME_TOKEN_TAG = 'UsernameToken',
  TRANSPORT_BINDING_TAG = 'TransportBinding',
  SUPPORTED_SAML_VERSIONES = ['WssSamlV20Token11', 'WssSamlV11Token11', 'WssSamlV11Token10', 'WssSamlV20Token11'],
  USERNAME_PASSWORD_TYPES = ['NoPassword', 'HashPassword', 'Normal'],
  SAML_TOKEN_TAG = 'SamlToken';

module.exports = {
  TOKEN_KINDS,
  POLICY_TAG,
  TOKEN_TYPES,
  ATRIBUTE_INCLUDE_TOKEN,
  NO_PASSWORD_TAG,
  HASH_PASSWORD_TAG,
  USERNAME_TOKEN_TAG,
  SAML_TOKEN_TAG,
  TRANSPORT_BINDING_TAG,
  SUPPORTED_SAML_VERSIONES,
  USERNAME_PASSWORD_TYPES,
  NORMAL_PASSWORD_TAG
};
