const ERROR_ELEMENT_IDENTIFIER = 'error',
  HTTP_PROTOCOL = 'HTTP',
  SOAP_ENVELOPE_NS_URL = 'http://schemas.xmlsoap.org/soap/envelope/',
  SOAP_12_ENVELOPE_NS_URL = 'http://www.w3.org/2003/05/soap-envelope',
  MESSAGE_TAG_ENVELOPE = 'Envelope',
  MESSAGE_TAG_BODY = 'Body',
  SOAP_PROTOCOL = 'soap',
  MIME_TYPE_CONTENT = 'content',
  MIME_TYPE_XML = 'xml',
  URL_ENCODED = 'application/x-www-form-urlencoded',
  URL_ENCODED_GET = 'urlEncoded',
  SOAP12_PROTOCOL = 'soap12',
  EMPTY_ELEMENT_BY_DEFAULT = 'EMPTY_ELEMENT_BY_DEFAULT';


module.exports = {
  ERROR_ELEMENT_IDENTIFIER,
  HTTP_PROTOCOL,
  SOAP_ENVELOPE_NS_URL,
  SOAP_12_ENVELOPE_NS_URL,
  MESSAGE_TAG_ENVELOPE,
  MESSAGE_TAG_BODY,
  SOAP_PROTOCOL,
  SOAP12_PROTOCOL,
  MIME_TYPE_CONTENT,
  MIME_TYPE_XML,
  URL_ENCODED,
  URL_ENCODED_GET,
  EMPTY_ELEMENT_BY_DEFAULT
};
